spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://devopsusa.com:3306/db_ecommerce
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true

server:
  port: 8083

eureka:
  instance:
    hostname: ${HOST_NAME}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: https://springboot-discovery.herokuapp.com/eureka


